### ISSUE TITLE
itry to login into my account and this masseage show 

### ISSUE THREAD

**Issue by ano15Games** [Tustin/PlayStationDiscord#188]
![Screenshot_29](https://user-images.githubusercontent.com/89452937/130594155-b03e357c-6934-40fb-b809-e6c86b21c4c4.png)

**Comment by TheUnrealLPJ** [comment]
same error

**Comment by Azekthi** [comment]
I'm having the same error. If it helps, I'm getting a verification puzzle when I log in, but the error shows up after successfully completing that puzzle. My account has two-step verification, but it doesn't reach that point.

**Comment by TheUnrealLPJ** [comment]
just restarted my router and my pc and after 2 hours ive waited it worked so try this maybe

**Comment by abi6ail** [comment]
I'm on macOS Big Sur and PS4.

Finally decided to change my PSN after 10+ years and then went to open PlayStationDiscord (3.1.2) and was signed out for obvious reasons. I couldn't log in due to the same error everyone else is facing (PlayStation thinks you're a bot, blah blah blah). Over the course of the night I left the app open for long periods of time and would keep trying... I installed different versions and tried those etc etc.

**What worked for me** was starting from scratch. I uninstalled everything, re-downloaded 3.1.2 and changed my Wi-Fi network to my iPhone's hotspot THEN restarted my laptop. (When my laptop started up again it automatically connected to my usual wifi.... so I connected to my iPhone's hotspot again but didn't bother restarting).
I launched the app, attempted to login, but it didn't work. I closed the app again, changed to my normal Wi-Fi network, launched the app and logged in... I got the verification puzzle BUT THEN I got the 2fa and was finally in.

It's honestly a luck thing at this point but don't give up as there seems to be a lot of quirky ways that works for people.

**Comment by junglookatyou** [comment]
im also encountering the same issue for a while, but I finally got my hand on a ps5 so i don't know if this is not compatible with it yet but if anyone can help that be great! but ill keep trying to see if I can get lucky...

**Comment by cufish** [comment]
Same issue using the latest version, 3.1.2 does work fine... no PS5 support though

**Comment by aquelemiguel** [comment]
Also having this problem.

**Comment by EricHardiman** [comment]
> Same issue using the latest version, 3.1.2 does work fine... no PS5 support though
> 
> edit: after some messing around I managed to get it to work by logging in on 3.1.2, updating to 3.2.0 and praying the cookies stuck around. Was the 4th attempt or so (was messing around with backing up the %appdata% folder and just when I wanted to replace the new folder wit hthe old one I somehow managed to stayed logged on through the update lol)

Thank you for the explanation, that worked for me as well just now. Installed 3.1.2, logged in, copied the playstationdiscord folder in App Data to my desktop, updated it to 3.2.0 through the app, and then pasted + overwrote the content in the newly updated App Data folder with the 3.1.2 one on my desktop.

Thanks!

**Comment by astonat** [comment]
same issue, first time trying to use

**Comment by Jarsky** [comment]
Having this exact same issue. It was working. I've since upgraded to Windows 11 and just launched it and it wants me to sign in. Keep getting the same error, despite login working fine for my actual PS4 / PS5.
