### ISSUE TITLE
Where is games.txt?

### ISSUE THREAD

**Issue by vvirtues** [Tustin/PlayStationDiscord#195]
IK IM DUMB BUT PLEASE I need to update covers of some games

**Comment by joshlopes** [comment]
Is in a different repository. https://github.com/Tustin/PlayStationDiscord-Games all you had to do was read README !

**Comment by mdnpascual** [comment]
I finally learned how to fully works. It's not easy and needs a lot of work because you need to:

1) Pull this project (Needs to npm install) and modify the URL in `SupportedGames.ts` on your own games.json
2) Pull the PlayStationDiscord-Games (Needs to python install). Modify the games.yaml file with the appropriate title IDs that you want then run script.py
3) Create your own Discord Developer Application. Get the client_id and modify `discord_assets.py`
3) Run `discord_push.py`
4) Wait for AT LEAST 10 minutes
5) npm run start. And hopefully you don't get stuck on A Connection to the Server could not be established when logging on.

And then, if everything is correct. You should see your game in rich presence.
