### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by dylanhughes15** [Tustin/PlayStationDiscord#22]
Is it possible to add this to server side of my discord server? I know the program works on my end as I have the program but it possible to make server side so everyone can use it without having it downloaded?

**Comment by Tustin** [comment]
I don't think so unfortunately. Mostly because I don't believe there's a way you can update a user's status even if you have a token with full permissions to their account. The only way I've ever seen it done is through RPC which means you have to use it on the same PC as your Discord account is logged in on.

**Comment by dylanhughes15** [comment]
Ok, thanks for your response.
