### ISSUE TITLE
Desktop icon messed up

### ISSUE THREAD

**Issue by deejbruce** [Tustin/PlayStationDiscord#32]
Not sure why but when it's on the taskbar it's a bit glitched

The program itself works fine, Just looks odd, Wouldn't be much of an issue if I could minimise it to the notification area but that's just a minor issue.

![ddnsfox3r5](https://user-images.githubusercontent.com/7811248/53030323-7d970780-3462-11e9-83bd-3efd0cf162fb.png)

**Comment by deejbruce** [comment]
Also another issue since I know the program was re-written but Vita games are showing up as PS4 Games on Discord.  I thought I'd just add it to this thread than make another one.
![discord_d5ngfodj5x](https://user-images.githubusercontent.com/7811248/53030287-6bb56480-3462-11e9-9db0-ad8530426792.png)

**Comment by Tustin** [comment]
Icon messed up because I build the program icons automatically when I build the rest of the program so I think the size of the original image is too small which causes the other icons to mess up as well.

I've added support for both minimizing to tray and other PlayStation consoles on the `development` branch and these changes will be in the next update 😄

**Comment by deejbruce** [comment]
Thanks, I thought it was an issue with my monitor or the program itself so re-installed it.

**Comment by ThaTiemsz** [comment]
This issue is back again.
