### ISSUE TITLE
Wide Menu Bar Icon 

### ISSUE THREAD

**Issue by ErickJR13** [Tustin/PlayStationDiscord#41]
<img width="1680" alt="Screen Shot 2019-03-08 at 8 00 03 PM" src="https://user-images.githubusercontent.com/18079184/54063817-25d7fa80-41dd-11e9-85ba-66ecb47881a7.png">

PlaystationDiscord takes up about 8-9 icons on the Menu Bar. Any way this can be shrinked to one icon space?

**Comment by Gilles123** [comment]
I'm seeing the same thing. It seems to be since version 3.0.1, which added menu functionality, but it looks to be trying to use the 603x603 logo.png and displaying that in the menu bar. Mac apps generally use a .icns file, which contains multiple sizes of an icon. Incidentally, that file is actually being included in the Mac app bundle but isn't being used from there. I don't know enough about Electron to be able to say how to fix that though other than maybe just using platform detection and pointing at different logo files.
