### ISSUE TITLE
Problem communicating with discord

### ISSUE THREAD

**Issue by vict2292** [Tustin/PlayStationDiscord#46]
This happens throughout multiple versions of the app.
![Screenshot_1](https://user-images.githubusercontent.com/1734285/56618640-87381980-6623-11e9-8c31-79994f15053c.png)

**Comment by skullkeeper94** [comment]
have discord open mate

**Comment by vict2292** [comment]
I have

**Comment by skullkeeper94** [comment]
That's weird, mine had that issue up until I opened Discord, then it was fine. Just assumed it had to be open to communicate

**Comment by Tustin** [comment]
Check %APPDATA%/PlayStationDiscord/log.log and let me know what that says. I need to fix that message box issue. The log should tell you exactly what the problem is.

**Comment by Keinta15** [comment]
I have the same problem, this is what is shown in the log

```[2019-09-20 15:55:03.407] [info] Updated rich presence
[2019-09-20 15:55:13.404] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
    at Timeout.setTimeout (D:\Program Files\PlaystationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at unrefdHandle (timers.js:509:7)
    at Timer.processTimers (timers.js:211:12)
[2019-09-20 15:55:16.024] [warn] DiscordController disconnected```

**Comment by sxdxlyn** [comment]
i realize this is an old thread but i made an account on here for this reason only, i am having issues connecting to discord on the app
ill installed and uninstalled 3 times, all not working
im able to sign in just fine and it shows my status on the app but it has an error saying it wont connect to discord, and i know ive done all the steps right because i read through the instructions and watched a recent video on it. whats up?
