### ISSUE TITLE
Crash opening

### ISSUE THREAD

**Issue by Frankity** [Tustin/PlayStationDiscord#6]
it crashes when i click the blue button,  this is the log which i got from Windows Event Viewer

`Aplicación: PlaystationDiscord.exe
Versión de Framework: v4.0.30319
 exceptión: Flurl.Http.FlurlHttpException
   en Flurl.Http.FlurlRequest+<HandleExceptionAsync>d__23.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   en Flurl.Http.FlurlRequest+<SendAsync>d__19.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en Flurl.Http.FlurlRequest+<SendAsync>d__19.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   en Flurl.Http.HttpResponseMessageExtensions+<ReceiveJson>d__0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   en PlayStationDiscord.Game+<FetchGames>d__0.MoveNext()

Información de la excepción: System.AggregateException
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   en System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)
   en System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Result()
   en PlayStationDiscord.MainWindow..ctor()

Información de la excepción: System.Windows.Markup.XamlParseException
   en System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   en System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   en System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   en System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   en System.Windows.Application.LoadComponent(System.Uri, Boolean)
   en System.Windows.Application.DoStartup()
   en System.Windows.Application.<.ctor>b__1_0(System.Object)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   en MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   en System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   en MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   en MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   en System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   en System.Windows.Application.RunDispatcher(System.Object)
   en System.Windows.Application.RunInternal(System.Windows.Window)
   en System.Windows.Application.Run(System.Windows.Window)
   en PlayStationDiscord.App.Main()

`

**Comment by Tustin** [comment]
What version of Windows are you running?

**Comment by Frankity** [comment]
8.1

**Comment by daemonum** [comment]
Got a similar crash at the start.I don't even see the blue button or sign up screen at all.The progress doesn't get terminated i can still see it in my task manager.I'm using Windows 10.Although it's not fully in English due to my system Language but here is my Event Viewer log.

`
Uygulama: PlayStationDiscord.exe Framework Sürümü: v4.0.30319 Açıklama:  İşlenmeyen bir özel durum nedeniyle işlem sonlandırıldı. Özel Durum Bilgisi:  System.IO.FileNotFoundException konum:  PlayStationDiscord.UpdateChecker.get_Latest() konum:  PlayStationDiscord.MainWindow..ctor() Özel Durum Bilgisi:  System.Windows.Markup.XamlParseException konum:  System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader,  System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object,  System.Xaml.XamlObjectWriterSettings, System.Uri) konum:  System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean,  System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) konum:  System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream,  System.Windows.Markup.ParserContext, System.Object, Boolean) konum:  System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream,  System.Windows.Markup.ParserContext) konum:  System.Windows.Application.LoadComponent(System.Uri, Boolean) konum:  System.Windows.Application.DoStartup() konum:  System.Windows.Application.<.ctor>b__1_0(System.Object) konum:  System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,  System.Object, Int32) konum:  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,  System.Delegate, System.Object, Int32, System.Delegate) konum:  System.Windows.Threading.DispatcherOperation.InvokeImpl() konum:  System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)  konum:  MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)  konum:  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) konum:  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) konum:  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object) konum:  MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext,  System.Threading.ContextCallback, System.Object) konum:  System.Windows.Threading.DispatcherOperation.Invoke() konum:  System.Windows.Threading.Dispatcher.ProcessQueue() konum:  System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr,  Boolean ByRef) konum: MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr,  IntPtr, Boolean ByRef) konum:  MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) konum:  System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,  System.Object, Int32) konum:  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,  System.Delegate, System.Object, Int32, System.Delegate) konum:  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,  System.TimeSpan, System.Delegate, System.Object, Int32) konum:  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) konum:  MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)  konum:  System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)  konum:  System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)  konum: System.Windows.Application.RunDispatcher(System.Object) konum:  System.Windows.Application.RunInternal(System.Windows.Window) konum:  System.Windows.Application.Run(System.Windows.Window) konum:  PlayStationDiscord.App.Main()
--



`

**Comment by Tustin** [comment]
Hm alright, thanks for the logs. If it's crashing before startup, try looking in your Program Files directory (x86 folder if you are on 64 bit) and see if you have all of these files in there
![](https://i.imgur.com/3WwwKTJ.png)

If that looks ok, try checking your app data directory (%appdata%\PlayStationDiscord) and see if that directory exists and if so, you _should_ see a log.txt file in there at the very least. I don't log any app crashes in there currently but if that file (or the folder itself) doesn't exist, that's probably why it's crashing. I'll add some more useful crash logging in a bit to hopefully solve the issue.

As for @Frankity, if it crashes when you click the button, it's more than likely an issue with the webView control I switched to that makes the login form much faster and more responsive than before. It's my first time using it and it's not really natively supported in .NET yet so there might be some gotchas that I don't know about.

**Comment by Frankity** [comment]
ok, all my files are ok, that log file does not exist, i've created but still crashes when i click on blue button, i hope you can fix it, thanks for response.

**Comment by daemonum** [comment]
All the files were there and also log folder didn't exist.I solve the problem by updating Windows.If I remember correctly I was using either version 1703 or 1709.Updating to 1809 fixed the problem ( probably KB4230204 or KB4462919 ). Thank you for helping.

**Comment by Tustin** [comment]
What I'll probably do is have it fallback to the old web browser view if the new one won't work so you'll at least be able to try to login with the program.

**Comment by Tustin** [comment]
An update to this: I have implemented the fallback for the login form to hopefully prevent this error but there's still a thing or two I want to include before I push an update. However it should be up by the weekend.

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
