### ISSUE TITLE
macOS broken menu bar icon

### ISSUE THREAD

**Issue by xstecky** [Tustin/PlayStationDiscord#71]
**Information**
- OS: macOS 10.13.6
- Version: Latest

**Describe the bug**
The menu bar icon on macOS is scaled incorrectly.

![Screen Shot 2020-01-09 at 1 27 58 AM](https://user-images.githubusercontent.com/57512084/72043554-7dbd1300-327f-11ea-92ef-96bd737d951b.png)

**Comment by roxaloxa** [comment]
I fixed this in https://github.com/Tustin/PlayStationDiscord/pull/51 last year, but there hasn't been a new build/release in a long time. 😢

**Comment by Tustin** [comment]
I actually have a draft for the newest version ready. I had some issues because I decided it would be a good idea to try porting my Travis-CI auto-deploy script to GitHub Actions without knowing anything about how it worked 😛. Not a good idea but it does seem to be working now; I just need to figure out a small issue one of the updated packages introduced. Should be out very soon!

**Comment by Tustin** [comment]
Should be fixed the v3.1.0 since it's finally out.
