### ISSUE TITLE
Name of the game in the status rather than just Playstation 4

### ISSUE THREAD

**Issue by Zelly** [Tustin/PlayStationDiscord#96]
Instead of having just "Playstation 4" in the status, change it to whatever game I am playing at the time.  
  
Maybe something like "Playing Overwatch on PS4"  
  
It would be much more useful for me since most people I know don't click on profile actively(to see more details).

**Comment by Mahdios** [comment]
That's impossible due to the way discord applications work, implementing your suggestion would mean creating a seperate application for every game , uploading it's own assets and remembering the client id not to mention the limit of 10 applications per user wich is way lower than the current number of supported games. Hope this clarifies this subject for you.
